### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [Pixiepa1/prj-rev-bwfs-dasmoto#6]
Satisfactory 👍 

You've got a really good handle on basic CSS properties, demonstrated by your reproducing the web page exactly. Great job!

Try to get into the habit of giving your img tags alt attributes to improve your website's accessibility and keep your HTML organized by putting related sections of code into a container div.

See if you can make your code better by including some semantic HTML5 elements. These are elements like `header`, `footer`, `main`, and `section`, that describe your webpage a little more than the traditional `div`.

**Comment by Pixiepa1** [comment]
Thanks!
